{
  "bug_location": "Unknown",
  "severity": 3,
  "categories": [
    "Unknown"
  ],
  "root_cause": "N/A - Analysis failed",
  "issue_number": 8537,
  "title": "cases::test_gc_worker::test_notify_observer_after_apply will panic"
}